### ISSUE TITLE
Deluxe Paint AGA 

### ISSUE THREAD

**Issue by markusbkk** [steffest/DPaint-js#14]
Just curious.

Would changing the Amiga output to a Deluxe Paint version with AGA support require a lot of work outside of using an ADF with the right release and removing the 32 color limitations?
I wanna look at it myself when I have some time, but I figure I'd ask you first.

**Comment by steffest** [comment]
Not at all.
The main reason why I didn't include it, is because you then need at least a kickstart 3.0 rom and - weirdly enough - that's still under license and commercially available, so I can't really include it :-/ 
Last time I checked, Deluxe Paint AGA didn't work with the freely available AROS rom.
Perhaps there could be an option somewhere to set which Deluxe Paint version you want to launch and a way to provide your own roms when you want AGA, but at the same time I'd like to keep it "as simple as possible"

**Comment by markusbkk** [comment]
Awesome, thanks! So exporting to an IFF of more than 32 colors would not be an issue either then, I assume (I saw DPaint.js already supports 24 bit IFF imports)?

Once I figured out how to properly flood fill with a gradient (seems a bit different, coming from Aseprite. When I pick the gradient fill tool, it applies the gradient dither to the entire screen rather than just an area between pixels (which is great, too. For different use cases), DPaint.js might become my new go-to for pixel art.

**Comment by steffest** [comment]
Currently Dpaint.js supports saving IFF up to 256 colors.

and indeed: that whole "limit paint operation to selection" thing needs work in dpaint.js :-/
It's on the TODO list!

**Comment by markusbkk** [comment]
> Currently Dpaint.js supports saving IFF up to 256 colors.
> 

Ah. Ok. So it's just the preview that's limited to 32 colors, due to using Deluxe Paint II. I was confused because the README reads `Writes IFF ILBM images (up to 32 colors)`

> and indeed: that whole "limit paint operation to selection" thing needs work in dpaint.js :-/ It's on the TODO list!

I wasn't sure if it's a bug or a feature. Glad to know it's a TODO.

**Comment by steffest** [comment]
Right! The documentation was lagging :-)
That's updated.

**Comment by markusbkk** [comment]
> Right! The documentation was lagging :-) That's updated.

Awesome! Thanks for the great work. I really enjoy using DPaint.js.
Did the banner for my game's Kickstarter campaign with it and plan on doing the entire game with it, too.

I linked to DPaint.js from my Kickstarter campaign (mentioned that I was using DPaint.js for my project). Hope you don't mind.
