### ISSUE TITLE
Suggestions about the channels and TGA

### ISSUE THREAD

**Issue by kevincrans** [steffest/DPaint-js#16]
1. Adapting the channel depth to a given value (4 bit per channel)
2. Adding Transparency
3. ~~Adding hexadecimal presentation to right click colour menu (#FFFF)~~
4. Add 12-bit TGA support
5. I also hope when I right click the selected colour (which I got from colorpicker), that I can see the selected rgb values instead of 0, 0, 0

**Comment by steffest** [comment]
Thanks! Good suggestions.

That "0, 0, 0" when clicking the selected color is in fact a bug. Yay, something to fix! :-)

Transparancy is already there, but it is a "brush" setting, not a color setting. (it's called opacity)
<img width="172" alt="image" src="https://github.com/steffest/DPaint-js/assets/763047/788ae351-f23b-4145-a21a-264c2a888033">

You can select a full transparent color by clicking that cross left-below the selected color
<img width="66" alt="image" src="https://github.com/steffest/DPaint-js/assets/763047/0fb5a1b8-fe07-4b75-b7fa-e2388a537075">

And yeay: that 4 bit/3bit color depth will certainly be added.

**Comment by kevincrans** [comment]
Thanks for the positive reaction.
I've also seen hexadecimal (like HCL) has been available for a long time.

**Comment by steffest** [comment]
This was closed as bug because point 5 has been fixed.
The suggestions have been added to my suggestion list.
