### ISSUE TITLE
Support for DPaint  DOS LBM files?

### ISSUE THREAD

**Issue by warpdesign** [steffest/DPaint-js#18]
Does DPaint-js support `.lbm` files from the DOS version of Deluxe Paint? These are IFF files with a `PBM  ` FORM and a chunky body instead of interleaved bitplanes like in Amiga ILBM files.

**Comment by steffest** [comment]
Yes,
This repository and the development version on https://www.stef.be/dpaint/dev/ already support it.
It will be included in the "stable" version in the next release.
