### ISSUE TITLE
BUG: Disappearing layers

### ISSUE THREAD

**Issue by osraunio** [steffest/DPaint-js#20]
Sometimes when I press ctrl+z, maybe after having some hidden layer active, then changing layer visibility, the result is that one layer is duplicated over another layer, destroying the old content completely.

**Comment by steffest** [comment]
Ouch, thats sounds like a nasty one...
Sorry about that.

I'll look into.

**Comment by steffest** [comment]
Confirmed it's a bug.
Steps to reproduce:
- Start with 2 empty layers.
- Draw on layer 1
- Draw again on layer 1
- Undo
- Switch to layer 2
- Draw on layer 2
- Undo

Layer 1  is now (incorrectly) copied to layer 2, layer 1 is empty.
It seems the undo buffer is not correctly mapped to the active layer.
