### ISSUE TITLE
Background grid is blurry on MacOS Safari

### ISSUE THREAD

**Issue by kud1ing** [steffest/DPaint-js#30]
<img width="582" alt="Bildschirmfoto 2024-07-26 um 19 30 10" src="https://github.com/user-attachments/assets/d920218c-49c1-46be-af2b-d76e52ae28a8">

**Comment by steffest** [comment]
True.
You have trained eyes!
One of the many weird quircks and bugs of Safari ...

It's fixed now and will be part of the next release.
You can preview the fix on the dev version on https://www.stef.be/dpaint/dev/

Thanks!
