### ISSUE TITLE
Clicks on scrollers draw on canvas

### ISSUE THREAD

**Issue by grzegorz-kraszewski** [steffest/dpaint-js#4]
When canvas is zoomed in, so it gets scrollers, clicking on them (to scroll the canvas) "goes through" and draws on the canvas.
Steps to reproduce:
1. Select bigger brush, so the problem is better visible.
2. Zoom in until you get at least one scroller laying over the canvas.
3. Scroll a bit.
4. Zoom out, a dot is painted on the canvas.

**Comment by steffest** [comment]
Right! 
That was a clear bug. Thanks.
I never noticed it, because I always scroll with the touchpad or with space-drag.

Should be fixed now.
