### ISSUE TITLE
Add a "Duplicate Frame" button

### ISSUE THREAD

**Issue by tristanbob** [steffest/DPaint-js#5]
Primary goal:
- Add a new button to duplicate the current frame (and insert the new frame after the current frame)

Secondary goal:
- Always highlight the current selected frame (so it's obvious which one will be deleted or duplicated)

Thanks for the great software!

**Comment by steffest** [comment]
Right!
Good point.

I must say the entire "frames" thing is a bit underdeveloped currently.
I had a prototype for animation in place, but I left it out for now because it was too unfinished to release.

but indeed: a "duplicate frame" option is a must.

**Comment by steffest** [comment]
That's added. (Right click on a frame) 
You can also now drag the frames to reorder them.

![image](https://user-images.githubusercontent.com/763047/232011995-7977dc28-5670-46c9-86e8-a5d7ea8d07fe.png)
