### ISSUE TITLE
Moving quickly with the pencil tool results in gaps

### ISSUE THREAD

**Issue by tristanbob** [steffest/DPaint-js#9]
When drawing with the pencil tool, gaps can appear if the cursor is moved quickly.  It seems to only draw once per frame.

Possible solution:
- When drawing with the pencil, always draw a straight line between the position of cursor last frame and the current frame

![image](https://user-images.githubusercontent.com/8879811/234649011-c086a288-af56-4889-9fd5-0dca2084908c.png)

**Comment by steffest** [comment]
Indeed. I'm still pondering over the best approach for this.
Of course in Deluxe Paint this is a separate button, but I don't want to overload the UI with too much buttons.
Probably the line approach is best,
